### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "org.cyclonedx.model.Component.getGroup()" because the return value of "org.cyclonedx.model.Metadata.getComponent()" is null

### ISSUE THREAD

**Issue by martinleim** [medavis-gmbh/LicenseComplianceTool#34]
Recently, `cyclonedx-maven-plugin` version [2.8.0](https://github.com/CycloneDX/cyclonedx-maven-plugin/releases/tag/cyclonedx-maven-plugin-2.8.0) has been released. Starting from this version, SBOMs are created in version 1.5. When reading such a file, the following error occurs:

```
java.lang.NullPointerException: Cannot invoke "org.cyclonedx.model.Component.getGroup()" because the return value of "org.cyclonedx.model.Metadata.getComponent()" is null
        at de.medavis.lct.core.asset.AssetLoader.loadFromBom(AssetLoader.java:46)
        at de.medavis.lct.core.list.ComponentLister.listComponents(ComponentLister.java:65)
        at de.medavis.lct.cli.CreateManifest.call(CreateManifest.java:55)
        at de.medavis.lct.cli.CreateManifest.call(CreateManifest.java:38)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at de.medavis.lct.cli.Main.<init>(Main.java:36)
        at de.medavis.lct.cli.Main.main(Main.java:40)
```

LicenseComplianceTools should support both versions 1.4 and 1.5.

**Comment by martinleim** [comment]
Fixed with https://github.com/medavis-gmbh/LicenseComplianceTool/commit/605413543b2e46aa60cb7faebce4f7f0a3c1ae5b

**Comment by martinleim** [comment]
Fixed with https://github.com/medavis-gmbh/LicenseComplianceTool/commit/605413543b2e46aa60cb7faebce4f7f0a3c1ae5b
